# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# Mod properties
mod_version = 0.7.1
release_channel = beta
maven_group = de.mrjulsen.crn
archives_name = createrailwaysnavigator
main_class_name = CreateRailwaysNavigator
enabled_platforms = fabric,forge
java_version = 17
datapack_version = 9

# Mod Info
display_name = Create Railways Navigator
authors = MrJulsen
description = Get possible train connections in your world from one station to another using the Create Railways Navigator. An addon for the Create Mod.
homepage = https://www.curseforge.com/minecraft/mc-mods/create-railways-navigator
issues = https://github.com/MisterJulsen/Create-Train-Navigator/issues
source = https://github.com/MisterJulsen/Create-Train-Navigator
license = GNU General Public License v3.0
icon = icon.png
discord = https://discord.gg/AeSbNgvc7f

# Minecraft properties
minecraft_version = 1.18.2
parchment_version = 2022.11.06
next_unsupported_minecraft_version=1.19

# Dependencies
architectury_api_version = 4.11.93
fabric_loader_version = 0.15.11
fabric_api_version = 0.77.0+1.18.2
forge_version = 1.18.2-40.2.21
forge_version_int = 40

dragonlib_version = 2.2.22
modmenu_version = 3.2.5
forge_config_api_port_version = 3.2.4
create_fabric_version = 0.5.1-f-build.1333+mc1.18.2
create_forge_version = 0.5.1.e-318
registrate_forge_version = MC1.18.2-1.1.3
flywheel_forge_version = 0.6.10-105