org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true

# Mod properties
mod_version = 0.9.0-C6
build_number = 2
release_channel = beta
mod_id = createrailwaysnavigator
maven_group = de.mrjulsen.crn
archives_name = createrailwaysnavigator
main_class_name = CreateRailwaysNavigator
enabled_platforms = forge,fabric
java_version = 17
datapack_version = 15

# Mod Info
display_name = Create Railways Navigator
authors = MrJulsen
description = Get possible train connections in your world from one station to another using the Create Railways Navigator. An addon for the Create Mod.
homepage = https://www.curseforge.com/minecraft/mc-mods/create-railways-navigator
issues = https://github.com/MisterJulsen/Create-Train-Navigator/issues
source = https://github.com/MisterJulsen/Create-Train-Navigator
license = GNU General Public License v3.0
icon = icon.png
discord = https://discord.gg/AeSbNgvc7f

# Minecraft properties
minecraft_version = 1.20.1
parchment_version = 2023.09.03
next_unsupported_minecraft_version=1.21

# Dependencies
## Modloader
fabric_loader_version = 0.15.11
fabric_api_version = 0.90.4+1.20.1
forge_version = 1.20.1-47.2.1
forge_loader_version = 47
forge_dependency_version = 47

## Base Dependencies
architectury_api_version = 9.1.12
dragonlib_version = 3.0.20-beta
forge_config_api_port_version = 8.0.0
modmenu_version = 7.2.2

## Create Dependencies
create_fabric_version = 6.0.7.0+mc1.20.1-build.1716
create_fabric_dependency_version = 6.0.7
create_forge_version = 6.0.7-281
create_forge_dependency_version = 6.0.7
ponder_forge_version = 1.0.91
flywheel_forge_version = 1.0.5
registrate_forge_version = MC1.20-1.3.3