architectury {
    common rootProject.enabled_platforms.split(',')
}

def refmapName = "${rootProject.archives_name}-refmap.json"

loom {
    accessWidenerPath = file("src/main/resources/createrailwaysnavigator.accesswidener")
    mixin {
        defaultRefmapName = refmapName
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modCompileOnly "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.3"))
    implementation("io.github.llamalad7:mixinextras-forge:0.5.3")
    

    modImplementation("dev.architectury:architectury-fabric:${rootProject.architectury_api_version}")
    modImplementation("com.electronwill.night-config:toml:3.6.0")
    modImplementation("com.terraformersmc:modmenu:${rootProject.modmenu_version}")
    modImplementation("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${rootProject.forge_config_api_port_version}")
    modImplementation("de.mrjulsen.mcdragonlib:dragonlib-fabric:${rootProject.minecraft_version}-${rootProject.dragonlib_version}")
    
    modImplementation("com.simibubi.create:create-fabric-${rootProject.minecraft_version}:${rootProject.create_fabric_version}")


    modCompileOnly("mezz.jei:jei-${rootProject.minecraft_version}-forge-api:${rootProject.jei_version}")
    modRuntimeOnly("mezz.jei:jei-${rootProject.minecraft_version}-forge:${rootProject.jei_version}")
    modImplementation("maven.modrinth:tramways:0.3.3-fabric")
}