architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = file("src/main/resources/createrailwaysnavigator.accesswidener")
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modCompileOnly "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"
    //forge "net.minecraftforge:forge:$rootProject.forge_version"

    //modCompileOnly("dev.architectury:architectury:${rootProject.architectury_api_version}")
    //modCompileOnly("com.electronwill.night-config:toml:3.6.0")
    //modCompileOnly("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${rootProject.forge_config_api_port_version}")    
    //modImplementation("de.mrjulsen.mcdragonlib:dragonlib-fabric:${rootProject.minecraft_version}-${rootProject.dragonlib_version}")
    
    //modCompileOnly("dev.architectury:architectury-forge:${rootProject.architectury_api_version}")
    //modImplementation("de.mrjulsen.mcdragonlib:dragonlib-forge:${rootProject.minecraft_version}-${rootProject.dragonlib_version}")
//
    //modImplementation("com.simibubi.create:create-${rootProject.minecraft_version}:${rootProject.create_forge_version}:slim") { transitive = false }
    //modImplementation("net.createmod.ponder:Ponder-Forge-${rootProject.minecraft_version}:${rootProject.ponder_forge_version}")
    //modCompileOnly("dev.engine-room.flywheel:flywheel-forge-api-${rootProject.minecraft_version}:${rootProject.flywheel_forge_version}")
    //modRuntimeOnly("dev.engine-room.flywheel:flywheel-forge-${rootProject.minecraft_version}:${rootProject.flywheel_forge_version}")
    //modImplementation("com.tterrag.registrate:Registrate:${rootProject.registrate_forge_version}")

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation("io.github.llamalad7:mixinextras-forge:0.4.1")
    

    modImplementation("dev.architectury:architectury-fabric:${rootProject.architectury_api_version}")
    modImplementation("com.electronwill.night-config:toml:3.6.0")
    modImplementation("com.terraformersmc:modmenu:${rootProject.modmenu_version}")
    modImplementation("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${rootProject.forge_config_api_port_version}")
    modImplementation("de.mrjulsen.mcdragonlib:dragonlib-fabric:${rootProject.minecraft_version}-${rootProject.dragonlib_version}")
    
    modImplementation("com.simibubi.create:create-fabric-${rootProject.minecraft_version}:${rootProject.create_fabric_version}")
}